version: '3.4'

services:
  nexerapi:
    image: ${DOCKER_REGISTRY-}nexerapi
    build:
      context: .
      dockerfile: NexerAPI/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - postgresdb 

  postgresdb:
    image: postgres:16.4
    container_name: nexer_api_db
    environment:
      - POSTGRES_DB=nexer_challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
